site_name: XMT-WIKI
site_description: 'XMT WIKI'
site_author: 'KUAI'
site_url: 'https://docs.runmun.site/'

nav:
    - 主页: index.md
    - 基本信息:
        - 基本说明: base/baseinfo.md
        - 记住: base/remember.md
        - 地图: base/map.md
    - 表:
        - 名词表: table/verb.md
        - 常用快捷键: table/shortcut.md
        - 运行(Win): table/cmd.md
    - 关于: about.md
    
theme: 
    name: null
    custom_dir: "material/"
    language: 'zh'
    palette:
        primary: 'blue'
        accent: 'blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo:
        icon: 'cloud'
    feature:
        tabs: false


markdown_extensions:
    - admonition
    - codehilite