site_name: XMT-WIKI
site_description: 'XMT WIKI'
site_author: 'KUAI'
site_url: 'https://docs.runmun.site/'

nav:
    - 主页: index.md
    - 基本信息:
        - 基本说明: base/baseinfo.md
        - 说在前面: base/first.md
        - 记住: base/remember.md
        - 地图: base/map.md
        - 活动: base/activity.md
    - 表:
        - 名词表: table/verb.md
        - 常用快捷键: table/shortcut.md
        - 运行(Win): table/cmd.md
        - 扩展名: table/ext.md
        - 目录简写: table/dir.md
    - 指南:
        - 硬件: knowledge/hard.md
        - 软件: knowledge/soft.md
        - 梗: knowledge/meme.md
        - 翻墙: knowledge/wall.md
        - 其他一些有趣的事情: knowledge/interest.md
        - 设计相关: knowledge/design.md
    - 信息:
        - 基本信息: info/info.md
        - 硬件(设备)信息: info/device.md
        - 软件: info/software.md
        - 微软（Microsoft）系列: info/microsoft.md
    - Adobe系列:
        - Adobe概述: adobe/adobe.md
        - AE视频剪辑: adobe/ae.md
        - PS图片处理: adobe/ps.md
    - 编程:
        - 网页编程概述: program/web.md
        - HTML语言: program/html.md
        - CSS语言: program/css.md
        - JS语言: program/js.md
        - JSON格式: program/json.md
        - JQuery模块: program/jquery.md
        - SQL语言: program/sql.md
        - htaccess文件: program/htaccess.md
        - 正则表达式: program/regexp.md
        - 润梦专题: program/runmun.md
        - 浏览器: program/browser.md
        - 服务器: program/server.md
    - 关于: 
        - 关于: about/about.md
        - 更新日志: about/update.md
        - 语法和插件: about/grammar.md
        - Markdown（完整版）: about/markdown.md
        - 关于Mkdocs: about/mkdocs.md
theme: 
    name: null
    custom_dir: "material/"
    language: 'zh'
    palette:
        primary: 'blue'
        accent: 'blue'
    font:
        text: 'Ubuntu'
        code: 'Ubuntu Mono'
    logo:
        icon: 'cloud'
    feature:
        tabs: false

extra_css:
    - 'assets/toomuch.css'
extra_javascript:
    - 'assets/toomuch.js'

markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.inlinehilite
    - pymdownx.details
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tilde

